[project]
name = "cbtc"
authors = []
description = ""
telemetry = false
cache_dir = "/Users/ludovic/Coding/clarinet/clarinet-cli/examples/cbtc/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"
[contracts.cbtc-token]
path = "contracts/cbtc-token.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
