[project]
name = "cbtc"
authors = []
description = ""
telemetry = false

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[contracts.cbtc-token]
path = "contracts/cbtc-token.clar"
clarity_version = 1
epoch = "2.05"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
