[package]
name = "clarity-repl"
version = "0.28.1"
description = "Clarity REPL"
authors = ["Ludo Galabru <ludo@hiro.so>", "Brice Dobry <brice@hiro.so>", "Reed Rosenbluth <reed@hiro.so>"]
readme = "README.md"
edition = "2018"
license = "GPL-3.0-only"
keywords = ["blockstack", "blockchain", "clarity", "smart-contract", "repl"]
exclude = [
    "vs-client/**",
    ".husky",
    ".git*"
    ]
homepage = "https://hirosystems.github.io/clarity-repl/"
repository = "https://github.com/hirosystems/clarity-repl"
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]

[dependencies]
ansi_term = "0.12.1"
lazy_static = "1.4.0"
regex = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.47", features = ["unbounded_depth"] }
sha2 = "0.9.3"
sha3 = "0.9.1"
serde_derive = "1.0"
ripemd160 = "0.9.1"
integer-sqrt = "0.1.3"
libsecp256k1 = "0.5.0"
serde_stacker = "0.1"
rand = "=0.7.3"
getrandom = { version = "0.2.3", features = ["js"] }
rand_pcg = "0.3.1"
rand_seeder = "0.2.2"
atty = "0.2.14"

# DAP Debugger
tokio = { version = "=1.17.0", features = ["full"], optional = true }
tokio-util = { version = "0.7.1", features = ["codec"], optional = true }
futures = { version = "0.3.12", optional = true }
debug_types = { version = "1.0.0", optional = true }
httparse = { version = "1.6.0", optional = true }
bytes = { version = "1.1.0", optional = true }
log = { version = "0.4.16", optional = true }
memchr = { version = "2.4.1", optional = true }

# CLI
pico-args = { version = "0.4.0", optional = true }
rustyline = { version = "9.1.1", optional = true }
prettytable-rs = { version = "0.8.0", optional = true }

# WASM
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4.24", optional = true }

[lib]
name = "clarity_repl"
path = "src/lib.rs"
# Default type
# crate-type = ["lib"]

# Use this instead for WASM builds
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "clarity-repl"
path = "src/bin.rs"

[features]
default = ["cli", "dap"]
cli = ["pico-args", "rustyline", "prettytable-rs"]
dap = [
    "tokio",
    "tokio-util",
    "futures",
    "debug_types",
    "httparse",
    "bytes",
    "memchr",
    "log",
]
wasm = ["wasm-bindgen", "wasm-bindgen-futures"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false
